### ISSUE TITLE
Missing home modules in cabal file

### ISSUE THREAD

**Issue by ulysses4ever** [Maryann13/Zipper#1]
```
~$ git clone git@github.com:Maryann13/Zipper.git && cd Zipper
...
~/Zipper$ cabal install --only-dependencies
...
~/Zipper$ cabal repl
...
λ> :l test/Example.hs 

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules:
          Generics.Zipper
          Generics.Zipper.Base
          Generics.Zipper.GenericContext
          Generics.Zipper.GenericZipper

```

Can we get rid of the warning?

**Comment by abolotina** [comment]
I have removed this warning for compilation of tests via `cabal test`. But it remains for loading `Example.hs` through `cabal repl` of the library. I think it should be so, since the `Example` module doesn't belong to the library. It belongs to the `generic-zipper-example` test-suite in the `generic-zipper.cabal` file. This means that if you want to load this module using `cabal repl`, you should say:

```
cabal configure --enable-tests
cabal repl generic-zipper-example
```
